import { readFileSync, renameSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type pino from "pino";

export interface CredentialsPayload {
  id: number;
  webhook_secret: string;
  pem: string;
  client_id?: string;
  client_secret?: string;
  slug?: string;
  html_url?: string;
}

export const CREDENTIALS_FILENAME = "credentials.env";
export const TTL_MS = 3_600_000;

// Inverse of formatEnvFile — partial because consumers decide whether missing fields are fatal.
export function parseEnvFile(body: string): Partial<CredentialsPayload> {
  const idMatch = body.match(/^APP_ID=(\d+)/m);
  const whMatch = body.match(/^WEBHOOK_SECRET=(.+)$/m);
  const pemMatch = body.match(/^PRIVATE_KEY="([\s\S]+?)"/m);
  const result: Partial<CredentialsPayload> = {};
  // Capture group [1] is guaranteed by the regex shape; the .? guards strictNullChecks under noUncheckedIndexedAccess.
  const idGroup = idMatch?.[1];
  const whGroup = whMatch?.[1];
  const pemGroup = pemMatch?.[1];
  if (idGroup) result.id = Number(idGroup);
  if (whGroup) result.webhook_secret = whGroup;
  if (pemGroup) result.pem = pemGroup.replace(/\\"/g, '"');
  return result;
}

export function readCredentialsFile(dir: string): Partial<CredentialsPayload> {
  const file = join(dir, CREDENTIALS_FILENAME);
  try {
    return parseEnvFile(readFileSync(file, "utf8"));
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return {};
    throw e;
  }
}

export function formatEnvFile(payload: CredentialsPayload): string {
  if (payload.webhook_secret == null) {
    throw new Error(
      "formatEnvFile: webhook_secret is null/undefined — GitHub App manifest conversion must return a non-null webhook_secret. Refusing to write a broken .env.",
    );
  }
  const quotedPem = payload.pem.replace(/"/g, '\\"');
  return [
    `# Generated by auto-merge setup at ${new Date().toISOString()}`,
    "# DO NOT commit this file. TTL: 1 hour from creation.",
    `APP_ID=${payload.id}`,
    `WEBHOOK_SECRET=${payload.webhook_secret}`,
    "# PEM private key — newlines preserved via dotenv-compatible quoted form.",
    `PRIVATE_KEY="${quotedPem}"`,
    "",
  ].join("\n");
}

export interface CredentialsStore {
  persist(payload: CredentialsPayload): void;
  read(): Buffer | null;
  exists(): boolean;
  delete(): void;
  getPath(): string;
}

export function checkStaleOnBoot(dir: string, log: pino.Logger): void {
  const final = join(dir, CREDENTIALS_FILENAME);
  try {
    const st = statSync(final);
    if (st.mtimeMs < Date.now() - TTL_MS) {
      unlinkSync(final);
      log.info({ event: "setup_stale_cleanup", path: final, mtimeMs: st.mtimeMs }, "setup");
    }
  } catch (e) {
    // ENOENT is the steady state; non-ENOENT (EACCES, EIO) signals a deployment misconfig — surface it.
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  }
}

export function createCredentialsStore({
  dir,
  log,
}: {
  dir: string;
  log: pino.Logger;
}): CredentialsStore {
  const final = join(dir, CREDENTIALS_FILENAME);
  // Same-directory tmp suffix avoids EXDEV on cross-fs mounts (Pitfall 2).
  const tmpPath = `${final}.tmp-${process.pid}`;

  function persist(payload: CredentialsPayload): void {
    const body = formatEnvFile(payload);
    try {
      writeFileSync(tmpPath, body, { mode: 0o600 });
      renameSync(tmpPath, final);
    } catch (err) {
      try {
        unlinkSync(tmpPath);
      } catch {
        // tmp may not exist — best-effort cleanup, swallow silently.
      }
      throw err;
    }
    const handle = setTimeout(() => {
      try {
        unlinkSync(final);
        log.info({ event: "setup_credentials_expired", path: final }, "setup");
      } catch (e) {
        if ((e as NodeJS.ErrnoException).code !== "ENOENT") {
          log.warn({ err: e, event: "setup_ttl_unlink_failed", path: final }, "setup");
        }
      }
    }, TTL_MS);
    handle.unref();
  }

  function read(): Buffer | null {
    try {
      return readFileSync(final);
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return null;
      throw e;
    }
  }

  function exists(): boolean {
    try {
      return statSync(final).isFile();
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code === "ENOENT") return false;
      throw e;
    }
  }

  function del(): void {
    try {
      unlinkSync(final);
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
    }
    log.info({ event: "setup_credentials_deleted", path: final }, "setup");
  }

  return {
    persist,
    read,
    exists,
    delete: del,
    getPath: () => final,
  };
}
